package db

import (
	"database/sql"

	// "github.com/mattn/go-sqlite3" - NEEDED FOR LATER USE
)

// Loads / Creates a database given a map file
func LoadDatabase(filename string) (*Database,error) {
	db, err := sql.Open("sqlite3", filename+".db")
	if err != nil {
        return nil, err
	}

	tmpDB := new(Database)
	tmpDB.instance = db

	err = tmpDB.InitTables()
	if err != nil {
        return nil, err
	}
	return tmpDB, nil
}

// Create base tables for new players if applicable
// TODO: Make this generated by metadata in map - This will probably take some work and testing
func (db *Database) InitTables() error {
	query := `
    CREATE TABLE IF NOT EXISTS players(
        player_id INTEGER PRIMARY KEY AUTOINCREMENT,
        player_name TEXT NOT NULL UNIQUE, 
        curr_room_index SMALLINT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS inventory(
        inventory_id INTEGER PRIMARY KEY AUTOINCREMENT,
        player_id INTEGER NOT NULL,
        item TEXT NOT NULL,
        FOREIGN KEY (player_id) REFERENCES players(player_id)
    );
    `

	_, err := db.instance.Exec(query)
	return err
}
